version: '3.0'

services:
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
  web:
    image: alexcheng/magento
    ports:
      - "5000-5015:80"
    links:
      - db
    env_file:
      - env
    depends_on:
      - db
volumes:
  db-data: